### ISSUE TITLE
Wondering about the flow

### ISSUE THREAD

**Issue by dovahkrid** [rjtavares/BirdsPyView#4]
Why do it have to convert the image first, then mark the player position ? How about mark the player position first, then convert both the image and the position (using `getPerspectiveTransform` or something like that) ?
I'm not sure my idea is possible, just asking because the converted image is kinda hard to mark position.

**Comment by rjtavares** [comment]
Yes, it is totally possible. Ideally, you can pick where you want to mark the players: original or converted image.

I'll work on that possibility.

**Comment by rjtavares** [comment]
Added to option, but didn't do enough tests to make sure it's working properly.

![image](https://user-images.githubusercontent.com/4527709/93978506-00d1bb00-fd74-11ea-8c03-fb0c2932bd36.png)

If you could help test it, it would be great.

**Comment by dovahkrid** [comment]
Awesome. I will test it asap !

**Comment by dovahkrid** [comment]
OK the "original image" works. But there are some things I want to ask:

- Why there are 2 outputs ? What are the max, min of x, y ?
![Screen Shot 2020-09-23 at 21 04 33](https://user-images.githubusercontent.com/14861163/94023557-8db25e00-fde0-11ea-9c7f-734223697a17.png)

- When you suddenly drag the line outside the image, you can't control it anymore.
- I have to choose types of 4 lines before drawing the lines, which is a little confusing since all the drop-down(s) are below the image. Drawing before choosing types doesn't work.

They are all minor problems I get (not really serious to focus with urgent). But still this is an awesome project !

**Comment by rjtavares** [comment]
> Why there are 2 outputs ? What are the max, min of x, y ?

The first version is the correct one (x and y must be between 0 and 100), I have the delete the other. I'll fix it today.

> When you suddenly drag the line outside the image, you can't control it anymore.

I've noticed that, but it's a limitation of the component I'm using. I'll submit an issue there.

> I have to choose types of 4 lines before drawing the lines, which is a little confusing since all the drop-down(s) are below the image. Drawing before choosing types doesn't work.

Drawing before choosing types _should_ work, but you'll have to remember the order in which you created them. The process is very clunky at the moment, but the new Streamlit features will help it a lot (I think next version will have customized layouts, side by side should better in this part).

Thanks for the help!

**Comment by dovahkrid** [comment]
Since the original issue is solved. I close it now.
